# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/Twiddle_Factors_ROM/Twiddle_Factors_ROM.xci
# IP: The module: 'Twiddle_Factors_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/Twiddle_Factors_ROM/Twiddle_Factors_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Twiddle_Factors_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/Twiddle_Factors_ROM/Twiddle_Factors_ROM.xci
# IP: The module: 'Twiddle_Factors_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/Twiddle_Factors_ROM/Twiddle_Factors_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Twiddle_Factors_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
