# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/index31_rom/index31_rom.xci
# IP: The module: 'index31_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/index31_rom/index31_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'index31_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/index31_rom/index31_rom.xci
# IP: The module: 'index31_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_Project/NTT_Accelerator/NTT_Accelerator.srcs/sources_1/ip/index31_rom/index31_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'index31_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
